language: cpp
os:
  - linux
  - osx
before_install:
  - export STAGE=before_install
  - ./ci/travis.sh
script:
  - export STAGE=script
  - ./ci/travis.sh
after_success:
  - export STAGE=after_success
  - ./ci/travis.sh

addons:
  homebrew:
    packages:
      - qt5
      - node
    update: true

compiler:
  - gcc
dist: xenial
sudo: required

osx_image: xcode10.2

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
